images:
  image:
    repository: public.ecr.aws/docker/library/nextcloud
    tag: 30.0.6
  nginx_image:
    repository: public.ecr.aws/nginx/nginx
    tag: 1.27.4
  postgres_13_image:
    repository: public.ecr.aws/docker/library/postgres
    tag: 13.19
  postgres_17_image:
    repository: public.ecr.aws/docker/library/postgres
    tag: "17.3"
  redis_image:
    repository: bitnami/redis
    tag: 7.4.2
  imaginary_image:
    repository: nextcloud/aio-imaginary
    tag: "20250204_102259"

consts:
  nextcloud_container_name: nextcloud
  cron_container_name: cron
  perms_container_name: permissions
  redis_container_name: redis
  postgres_container_name: postgres
  nginx_container_name: nginx
  imaginary_container_name: imaginary
  imaginary_port: 9000
  db_name: nextcloud
  ssl_key_path: /etc/nginx-certs/private.key
  ssl_cert_path: /etc/nginx-certs/public.crt
  deprecation_warning: |
    You are using a deprecated configuration, where both data and html nextcloud files
    are stored in the same path. Please consider updating your configuration.
    If you are unsure how to proceed, feel free to open a github issue.<br/>
    The backwards compatibility will be removed in the next major release.

  packages:
    smbclient:
      additional_apt: ["libsmbclient-dev"]
      pecl: ["smbclient"]
      docker_php_ext: ["smbclient"]
      ldd: ["smbclient.so"]
